version: '3.8'

services:
  booking:
    image: angus25/booking-service:latest
    hostname: "booking"
    container_name: booking
    environment:
      - FilePath=../srv/files/
      - HostnameRabbit=rabbitmq-dev
    ports:
      - "5001:80"
    networks:
      - default
    volumes:
      - files:/srv/files
    depends_on:
      - rabbitmq

  planning:
    image: angus25/planning-service:latest
    hostname: "planning"
    container_name: planning
    environment:
      - FilePath=../srv/files/
      - HostnameRabbit=rabbitmq-dev
    ports:
      - "5002:80"
    networks:
      - default
    volumes:
      - files:/srv/files
    restart: on-failure
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:management
    hostname: "rabbitmq-dev"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - default

volumes:
  files:
    external: false

networks:
  default:
    driver: bridge
    name: mitnet
